sudo: required
services:
  - docker

before_install:
  - docker build -t fabioadani/react-test -f ./client/Dockerfile.dev  ./client

script:
  - docker run fabioadani/react-test npm run test -- --coverage

after_success:
  - docker build -t fabioadani/multi-client ./client
  - docker build -t fabioadani/multi-nginx ./ngnix
  - docker build -t fabioadani/multi-server ./server
  - docker build -t fabioadani/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push fabioadani/multi-client
  - docker push fabioadani/multi-nginx
  - docker push fabioadani/multi-server
  - docker push fabioadani/multi-worker